name: "old.sachahjkl.github.io"
description: "https://sachahjkl.github.io/old.sachahjkl.github.io/ - My personnal website where i put on display projects, news of interest and my résumé."
topics: []
homepage: "https://sachahjkl.github.io/old.sachahjkl.github.io/"
source:
  provider: github
  namespace: "sachahjkl"
  path: "sachahjkl/old.sachahjkl.github.io"
